#ifndef CODE_PROJECT_CONFIG_H_
#define CODE_PROJECT_CONFIG_H_

#define ESC_BENCH_MODE_DISABLED          (0U)
#define ESC_BENCH_MODE_CALIBRATION       (1U)
#define ESC_BENCH_MODE_MOTOR_SEQUENCE    (2U)

/* 正常固件必须保持 DISABLED/0U。 */
#define ESC_BENCH_MODE                   ESC_BENCH_MODE_DISABLED
#define ESC_BENCH_SAFETY_ACKNOWLEDGED    (0U)

#define CONTROL_BENCH_MODE_DISABLED      (0U)
#define CONTROL_BENCH_MODE_STICK_MIXER   (1U)
#define CONTROL_BENCH_MODE_IMU_LEVEL     (2U)
#define CONTROL_BENCH_MODE_IMU_RATE      (3U)
#define CONTROL_BENCH_MODE_IMU_CASCADE   (4U)
#define CONTROL_BENCH_MODE_RC_ATTITUDE   (5U)
#define CONTROL_BENCH_MODE_RC_YAW_RATE   (6U)
#define CONTROL_BENCH_MODE_FULL_CONTROL  (7U)
#define CONTROL_BENCH_MODE_POWERED_CONTROL (8U)
#define CONTROL_BENCH_MODE_SHADOW_CONTROL (9U)

/* 影子模式运行控制计算，但每个控制周期强制四路实际 PWM 为 1000 us。 */
#define CONTROL_BENCH_MODE               CONTROL_BENCH_MODE_SHADOW_CONTROL
#define CONTROL_BENCH_SAFETY_ACKNOWLEDGED (1U)
#define CONTROL_BENCH_ESC_POWER_ACKNOWLEDGED (0U)

#define TELEMETRY_SOURCE_CRSF            (0U)
#define TELEMETRY_SOURCE_EULER           (1U)
#define TELEMETRY_SOURCE_IMU_CALIBRATION (2U)
#define TELEMETRY_SOURCE_RC_COMMAND      (3U)
#define TELEMETRY_SOURCE_GPS             (4U)
#define TELEMETRY_SOURCE_FLOW_TOF        (5U)
#define TELEMETRY_SOURCE_MOTOR_OUTPUT    (6U)
#define TELEMETRY_SOURCE_FLIGHT_CONTROL  (7U)
#define TELEMETRY_SOURCE                 TELEMETRY_SOURCE_FLIGHT_CONTROL

#if ((ESC_BENCH_MODE != ESC_BENCH_MODE_DISABLED) && \
     (ESC_BENCH_MODE != ESC_BENCH_MODE_CALIBRATION) && \
     (ESC_BENCH_MODE != ESC_BENCH_MODE_MOTOR_SEQUENCE))
#error "Invalid ESC_BENCH_MODE"
#endif

#if ((ESC_BENCH_MODE != ESC_BENCH_MODE_DISABLED) && \
     (ESC_BENCH_SAFETY_ACKNOWLEDGED != 1U))
#error "Remove all propellers before acknowledging ESC bench mode"
#endif

#if ((CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_DISABLED) && \
     (CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_STICK_MIXER) && \
     (CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_IMU_LEVEL) && \
     (CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_IMU_RATE) && \
     (CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_IMU_CASCADE) && \
     (CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_RC_ATTITUDE) && \
     (CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_RC_YAW_RATE) && \
     (CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_FULL_CONTROL) && \
     (CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_POWERED_CONTROL) && \
     (CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_SHADOW_CONTROL))
#error "Invalid CONTROL_BENCH_MODE"
#endif

#if ((CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_DISABLED) && \
     (CONTROL_BENCH_SAFETY_ACKNOWLEDGED != 1U))
#error "Remove all propellers and disconnect ESC power before control bench mode"
#endif

#if ((CONTROL_BENCH_MODE == CONTROL_BENCH_MODE_POWERED_CONTROL) && \
     (CONTROL_BENCH_ESC_POWER_ACKNOWLEDGED != 1U))
#error "Explicit approval is required before powering ESCs in control bench mode"
#endif

#if ((CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_POWERED_CONTROL) && \
     (CONTROL_BENCH_ESC_POWER_ACKNOWLEDGED != 0U))
#error "ESC power acknowledgement must be cleared outside powered control mode"
#endif

#if ((ESC_BENCH_MODE != ESC_BENCH_MODE_DISABLED) && \
     (CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_DISABLED))
#error "ESC bench mode and control bench mode are mutually exclusive"
#endif

#if ((TELEMETRY_SOURCE != TELEMETRY_SOURCE_CRSF) && \
     (TELEMETRY_SOURCE != TELEMETRY_SOURCE_EULER) && \
     (TELEMETRY_SOURCE != TELEMETRY_SOURCE_IMU_CALIBRATION) && \
     (TELEMETRY_SOURCE != TELEMETRY_SOURCE_RC_COMMAND) && \
     (TELEMETRY_SOURCE != TELEMETRY_SOURCE_GPS) && \
     (TELEMETRY_SOURCE != TELEMETRY_SOURCE_FLOW_TOF) && \
     (TELEMETRY_SOURCE != TELEMETRY_SOURCE_MOTOR_OUTPUT) && \
     (TELEMETRY_SOURCE != TELEMETRY_SOURCE_FLIGHT_CONTROL))
#error "Invalid TELEMETRY_SOURCE"
#endif

#endif /* CODE_PROJECT_CONFIG_H_ */
