#ifndef CODE_PROJECT_CONFIG_H_
#define CODE_PROJECT_CONFIG_H_

/*
 * 构建配置只允许通过编译器宏选择，仓库默认值永远是不可驱动电机的 SAFE。
 * 这样测试授权不会作为 main 分支中的长期源码状态残留。
 */
#define PROJECT_BUILD_PROFILE_SAFE                  (0U)
#define PROJECT_BUILD_PROFILE_TETHERED_FIRST_HOP    (1U)
#define PROJECT_BUILD_PROFILE_CUSTOM_TEST           (2U)

#ifndef PROJECT_BUILD_PROFILE
#define PROJECT_BUILD_PROFILE                       PROJECT_BUILD_PROFILE_SAFE
#endif

/* 仅用于阻止误选危险 profile，不代表现场安全条件已经自动满足。 */
#define PROJECT_DANGEROUS_BUILD_ACK_VALUE            (0x54455448UL)

#ifndef PROJECT_DANGEROUS_BUILD_ACK
#define PROJECT_DANGEROUS_BUILD_ACK                  (0UL)
#endif

#define ESC_BENCH_MODE_DISABLED          (0U)
#define ESC_BENCH_MODE_CALIBRATION       (1U)
#define ESC_BENCH_MODE_MOTOR_SEQUENCE    (2U)

#define CONTROL_BENCH_MODE_DISABLED      (0U)
#define CONTROL_BENCH_MODE_STICK_MIXER   (1U)
#define CONTROL_BENCH_MODE_IMU_LEVEL     (2U)
#define CONTROL_BENCH_MODE_IMU_RATE      (3U)
#define CONTROL_BENCH_MODE_IMU_CASCADE   (4U)
#define CONTROL_BENCH_MODE_RC_ATTITUDE   (5U)
#define CONTROL_BENCH_MODE_RC_YAW_RATE   (6U)
#define CONTROL_BENCH_MODE_FULL_CONTROL  (7U)
#define CONTROL_BENCH_MODE_POWERED_CONTROL (8U)
#define CONTROL_BENCH_MODE_SHADOW_CONTROL (9U)
#define CONTROL_BENCH_MODE_PID_I_SHADOW    (10U)

#define PROP_LOAD_TEST_MODE_DISABLED       (0U)
#define PROP_LOAD_TEST_MODE_VIBRATION_BASELINE (1U)

#define TETHERED_FLIGHT_MODE_DISABLED           (0U)
#define TETHERED_FLIGHT_MODE_FIRST_HOP          (1U)

#define IMU_DIAGNOSTIC_MODE_DISABLED             (0U)
#define IMU_DIAGNOSTIC_MODE_RAW_REREAD            (1U)

/*
 * 原始采样异常捕获模式不运行电机控制，每个 IMU 周期强制四路 1000 us。
 * 它只记录首读、立即复读和原始 SPI 字节，不需要接通 ESC 动力。
 */
#define TELEMETRY_SOURCE_CRSF            (0U)
#define TELEMETRY_SOURCE_EULER           (1U)
#define TELEMETRY_SOURCE_IMU_CALIBRATION (2U)
#define TELEMETRY_SOURCE_RC_COMMAND      (3U)
#define TELEMETRY_SOURCE_GPS             (4U)
#define TELEMETRY_SOURCE_FLOW_TOF        (5U)
#define TELEMETRY_SOURCE_MOTOR_OUTPUT    (6U)
#define TELEMETRY_SOURCE_FLIGHT_CONTROL  (7U)

/*
 * RA6M5 同款 TPF/LC08 使用软件 I2C。以下档位只改变 GPIO 映射，不改变
 * 传感器协议；当前实机选择 P406=SCL、P409=SDA。
 * 替代引脚在当前固件中均未分配，但使用前仍须确认自制 PCB 已实际引出、
 * 没有外接上拉到 5 V，也没有连接其他板载器件。
 */
#define TPF_FLOW_PIN_PAIR_P411_P412       (0U)
#define TPF_FLOW_PIN_PAIR_P413_P414       (1U)
#define TPF_FLOW_PIN_PAIR_P408_P409       (2U)
#define TPF_FLOW_PIN_PAIR_P400_P401       (3U)
#define TPF_FLOW_PIN_PAIR_P402_P403       (4U)
#define TPF_FLOW_PIN_PAIR_P404_P405       (5U)
#define TPF_FLOW_PIN_PAIR_P406_P407       (6U)
#define TPF_FLOW_PIN_PAIR_P406_P409       (7U)
#ifndef TPF_FLOW_PIN_PAIR
#define TPF_FLOW_PIN_PAIR                 TPF_FLOW_PIN_PAIR_P406_P409
#endif

#if (PROJECT_BUILD_PROFILE == PROJECT_BUILD_PROFILE_SAFE)

#if (PROJECT_DANGEROUS_BUILD_ACK != 0UL)
#error "SAFE profile must not carry a dangerous-build acknowledgement"
#endif
#define ESC_BENCH_MODE                   ESC_BENCH_MODE_DISABLED
#define ESC_BENCH_SAFETY_ACKNOWLEDGED    (0U)
#define CONTROL_BENCH_MODE               CONTROL_BENCH_MODE_DISABLED
#define CONTROL_BENCH_SAFETY_ACKNOWLEDGED (0U)
#define CONTROL_BENCH_ESC_POWER_ACKNOWLEDGED (0U)
#define PROP_LOAD_TEST_MODE              PROP_LOAD_TEST_MODE_DISABLED
#define PROP_LOAD_TEST_AIRFRAME_RESTRAINED_ACKNOWLEDGED (0U)
#define PROP_LOAD_TEST_PROPELLERS_ACKNOWLEDGED (0U)
#define PROP_LOAD_TEST_ESC_POWER_ACKNOWLEDGED (0U)
#define TETHERED_FLIGHT_MODE             TETHERED_FLIGHT_MODE_DISABLED
#define TETHERED_FLIGHT_RESTRAINT_ACKNOWLEDGED (0U)
#define TETHERED_FLIGHT_PROPELLERS_ACKNOWLEDGED (0U)
#define TETHERED_FLIGHT_AREA_AND_KILL_ACKNOWLEDGED (0U)
#define TETHERED_FLIGHT_ESC_POWER_ACKNOWLEDGED (0U)
#define IMU_DIAGNOSTIC_MODE              IMU_DIAGNOSTIC_MODE_DISABLED

#elif (PROJECT_BUILD_PROFILE == PROJECT_BUILD_PROFILE_TETHERED_FIRST_HOP)

#if (PROJECT_DANGEROUS_BUILD_ACK != PROJECT_DANGEROUS_BUILD_ACK_VALUE)
#error "Tethered profile requires an explicit PROJECT_DANGEROUS_BUILD_ACK"
#endif
#define ESC_BENCH_MODE                   ESC_BENCH_MODE_DISABLED
#define ESC_BENCH_SAFETY_ACKNOWLEDGED    (0U)
#define CONTROL_BENCH_MODE               CONTROL_BENCH_MODE_DISABLED
#define CONTROL_BENCH_SAFETY_ACKNOWLEDGED (0U)
#define CONTROL_BENCH_ESC_POWER_ACKNOWLEDGED (0U)
#define PROP_LOAD_TEST_MODE              PROP_LOAD_TEST_MODE_DISABLED
#define PROP_LOAD_TEST_AIRFRAME_RESTRAINED_ACKNOWLEDGED (0U)
#define PROP_LOAD_TEST_PROPELLERS_ACKNOWLEDGED (0U)
#define PROP_LOAD_TEST_ESC_POWER_ACKNOWLEDGED (0U)
#define TETHERED_FLIGHT_MODE             TETHERED_FLIGHT_MODE_FIRST_HOP
#define TETHERED_FLIGHT_RESTRAINT_ACKNOWLEDGED (1U)
#define TETHERED_FLIGHT_PROPELLERS_ACKNOWLEDGED (1U)
#define TETHERED_FLIGHT_AREA_AND_KILL_ACKNOWLEDGED (1U)
#define TETHERED_FLIGHT_ESC_POWER_ACKNOWLEDGED (1U)
#define IMU_DIAGNOSTIC_MODE              IMU_DIAGNOSTIC_MODE_DISABLED

#elif (PROJECT_BUILD_PROFILE == PROJECT_BUILD_PROFILE_CUSTOM_TEST)

#if (PROJECT_DANGEROUS_BUILD_ACK != PROJECT_DANGEROUS_BUILD_ACK_VALUE)
#error "Custom test profile requires an explicit PROJECT_DANGEROUS_BUILD_ACK"
#endif
#if !defined(ESC_BENCH_MODE) || !defined(ESC_BENCH_SAFETY_ACKNOWLEDGED) || \
    !defined(CONTROL_BENCH_MODE) || \
    !defined(CONTROL_BENCH_SAFETY_ACKNOWLEDGED) || \
    !defined(CONTROL_BENCH_ESC_POWER_ACKNOWLEDGED) || \
    !defined(PROP_LOAD_TEST_MODE) || \
    !defined(PROP_LOAD_TEST_AIRFRAME_RESTRAINED_ACKNOWLEDGED) || \
    !defined(PROP_LOAD_TEST_PROPELLERS_ACKNOWLEDGED) || \
    !defined(PROP_LOAD_TEST_ESC_POWER_ACKNOWLEDGED) || \
    !defined(TETHERED_FLIGHT_MODE) || \
    !defined(TETHERED_FLIGHT_RESTRAINT_ACKNOWLEDGED) || \
    !defined(TETHERED_FLIGHT_PROPELLERS_ACKNOWLEDGED) || \
    !defined(TETHERED_FLIGHT_AREA_AND_KILL_ACKNOWLEDGED) || \
    !defined(TETHERED_FLIGHT_ESC_POWER_ACKNOWLEDGED) || \
    !defined(IMU_DIAGNOSTIC_MODE)
#error "Custom profile must define every mode and acknowledgement macro"
#endif

#else
#error "Invalid PROJECT_BUILD_PROFILE"
#endif

#ifndef TELEMETRY_SOURCE
#define TELEMETRY_SOURCE                 TELEMETRY_SOURCE_FLOW_TOF
#endif

/*
 * SAFE 默认用于 UP-T301/UP_T3-001 的 UPIX UART 诊断。若编译时显式把
 * TELEMETRY_SOURCE 改成其他来源，则恢复原 TPF/LC08 软件 I2C 诊断。
 * 两种采集都与 3DR 数传任务解耦，系留阶段均不占用飞行遥测。
 */
#if ((PROJECT_BUILD_PROFILE == PROJECT_BUILD_PROFILE_SAFE) && \
     (TELEMETRY_SOURCE != TELEMETRY_SOURCE_FLOW_TOF))
#define TPF_FLOW_DIAGNOSTIC_ENABLED       (1U)
#else
#define TPF_FLOW_DIAGNOSTIC_ENABLED       (0U)
#endif

#if ((ESC_BENCH_MODE != ESC_BENCH_MODE_DISABLED) && \
     (ESC_BENCH_MODE != ESC_BENCH_MODE_CALIBRATION) && \
     (ESC_BENCH_MODE != ESC_BENCH_MODE_MOTOR_SEQUENCE))
#error "Invalid ESC_BENCH_MODE"
#endif

#if ((ESC_BENCH_MODE != ESC_BENCH_MODE_DISABLED) && \
     (ESC_BENCH_SAFETY_ACKNOWLEDGED != 1U))
#error "Remove all propellers before acknowledging ESC bench mode"
#endif

#if ((CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_DISABLED) && \
     (CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_STICK_MIXER) && \
     (CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_IMU_LEVEL) && \
     (CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_IMU_RATE) && \
     (CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_IMU_CASCADE) && \
     (CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_RC_ATTITUDE) && \
     (CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_RC_YAW_RATE) && \
     (CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_FULL_CONTROL) && \
     (CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_POWERED_CONTROL) && \
     (CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_SHADOW_CONTROL) && \
     (CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_PID_I_SHADOW))
#error "Invalid CONTROL_BENCH_MODE"
#endif

#if ((CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_DISABLED) && \
     (CONTROL_BENCH_SAFETY_ACKNOWLEDGED != 1U))
#error "Remove all propellers and disconnect ESC power before control bench mode"
#endif

#if ((CONTROL_BENCH_MODE == CONTROL_BENCH_MODE_POWERED_CONTROL) && \
     (CONTROL_BENCH_ESC_POWER_ACKNOWLEDGED != 1U))
#error "Explicit approval is required before powering ESCs in control bench mode"
#endif

#if ((CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_POWERED_CONTROL) && \
     (CONTROL_BENCH_ESC_POWER_ACKNOWLEDGED != 0U))
#error "ESC power acknowledgement must be cleared outside powered control mode"
#endif

#if ((ESC_BENCH_MODE != ESC_BENCH_MODE_DISABLED) && \
     (CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_DISABLED))
#error "ESC bench mode and control bench mode are mutually exclusive"
#endif

#if ((PROP_LOAD_TEST_MODE != PROP_LOAD_TEST_MODE_DISABLED) && \
     (PROP_LOAD_TEST_MODE != PROP_LOAD_TEST_MODE_VIBRATION_BASELINE))
#error "Invalid PROP_LOAD_TEST_MODE"
#endif

#if ((PROP_LOAD_TEST_MODE != PROP_LOAD_TEST_MODE_DISABLED) && \
     (PROP_LOAD_TEST_AIRFRAME_RESTRAINED_ACKNOWLEDGED != 1U))
#error "A rated prop-load restraint is required before prop-load testing"
#endif

#if ((PROP_LOAD_TEST_MODE != PROP_LOAD_TEST_MODE_DISABLED) && \
     (PROP_LOAD_TEST_PROPELLERS_ACKNOWLEDGED != 1U))
#error "Propeller type, position, direction and fastening must be acknowledged"
#endif

#if ((PROP_LOAD_TEST_MODE != PROP_LOAD_TEST_MODE_DISABLED) && \
     (PROP_LOAD_TEST_ESC_POWER_ACKNOWLEDGED != 1U))
#error "Explicit ESC power approval is required before prop-load testing"
#endif

#if ((PROP_LOAD_TEST_MODE == PROP_LOAD_TEST_MODE_DISABLED) && \
     ((PROP_LOAD_TEST_AIRFRAME_RESTRAINED_ACKNOWLEDGED != 0U) || \
      (PROP_LOAD_TEST_PROPELLERS_ACKNOWLEDGED != 0U) || \
      (PROP_LOAD_TEST_ESC_POWER_ACKNOWLEDGED != 0U)))
#error "All prop-load acknowledgements must be 0U when the mode is disabled"
#endif

#if ((PROP_LOAD_TEST_MODE != PROP_LOAD_TEST_MODE_DISABLED) && \
     ((ESC_BENCH_MODE != ESC_BENCH_MODE_DISABLED) || \
      (CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_DISABLED)))
#error "Prop-load, ESC bench and control bench modes are mutually exclusive"
#endif

#if ((TETHERED_FLIGHT_MODE != TETHERED_FLIGHT_MODE_DISABLED) && \
     (TETHERED_FLIGHT_MODE != TETHERED_FLIGHT_MODE_FIRST_HOP))
#error "Invalid TETHERED_FLIGHT_MODE"
#endif

#if ((IMU_DIAGNOSTIC_MODE != IMU_DIAGNOSTIC_MODE_DISABLED) && \
     (IMU_DIAGNOSTIC_MODE != IMU_DIAGNOSTIC_MODE_RAW_REREAD))
#error "Invalid IMU_DIAGNOSTIC_MODE"
#endif

#if ((IMU_DIAGNOSTIC_MODE != IMU_DIAGNOSTIC_MODE_DISABLED) && \
     ((ESC_BENCH_MODE != ESC_BENCH_MODE_DISABLED) || \
      (CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_DISABLED) || \
      (PROP_LOAD_TEST_MODE != PROP_LOAD_TEST_MODE_DISABLED) || \
      (TETHERED_FLIGHT_MODE != TETHERED_FLIGHT_MODE_DISABLED)))
#error "IMU diagnostic mode and all motor-control test modes are mutually exclusive"
#endif

#if ((TETHERED_FLIGHT_MODE != TETHERED_FLIGHT_MODE_DISABLED) && \
     (TETHERED_FLIGHT_RESTRAINT_ACKNOWLEDGED != 1U))
#error "A rated central tether and fixed anchor are required"
#endif

#if ((TETHERED_FLIGHT_MODE != TETHERED_FLIGHT_MODE_DISABLED) && \
     (TETHERED_FLIGHT_PROPELLERS_ACKNOWLEDGED != 1U))
#error "Propeller type, position, direction and fastening must be acknowledged"
#endif

#if ((TETHERED_FLIGHT_MODE != TETHERED_FLIGHT_MODE_DISABLED) && \
     (TETHERED_FLIGHT_AREA_AND_KILL_ACKNOWLEDGED != 1U))
#error "A cleared area, pilot kill switch and separate power-cut operator are required"
#endif

#if ((TETHERED_FLIGHT_MODE != TETHERED_FLIGHT_MODE_DISABLED) && \
     (TETHERED_FLIGHT_ESC_POWER_ACKNOWLEDGED != 1U))
#error "Explicit ESC power approval is required for tethered flight"
#endif

#if ((TETHERED_FLIGHT_MODE == TETHERED_FLIGHT_MODE_DISABLED) && \
     ((TETHERED_FLIGHT_RESTRAINT_ACKNOWLEDGED != 0U) || \
      (TETHERED_FLIGHT_PROPELLERS_ACKNOWLEDGED != 0U) || \
      (TETHERED_FLIGHT_AREA_AND_KILL_ACKNOWLEDGED != 0U) || \
      (TETHERED_FLIGHT_ESC_POWER_ACKNOWLEDGED != 0U)))
#error "All tethered-flight acknowledgements must be 0U when disabled"
#endif

#if ((TETHERED_FLIGHT_MODE != TETHERED_FLIGHT_MODE_DISABLED) && \
     ((ESC_BENCH_MODE != ESC_BENCH_MODE_DISABLED) || \
      (CONTROL_BENCH_MODE != CONTROL_BENCH_MODE_DISABLED) || \
      (PROP_LOAD_TEST_MODE != PROP_LOAD_TEST_MODE_DISABLED)))
#error "Tethered flight and all bench/prop-load modes are mutually exclusive"
#endif

#if ((TELEMETRY_SOURCE != TELEMETRY_SOURCE_CRSF) && \
     (TELEMETRY_SOURCE != TELEMETRY_SOURCE_EULER) && \
     (TELEMETRY_SOURCE != TELEMETRY_SOURCE_IMU_CALIBRATION) && \
     (TELEMETRY_SOURCE != TELEMETRY_SOURCE_RC_COMMAND) && \
     (TELEMETRY_SOURCE != TELEMETRY_SOURCE_GPS) && \
     (TELEMETRY_SOURCE != TELEMETRY_SOURCE_FLOW_TOF) && \
     (TELEMETRY_SOURCE != TELEMETRY_SOURCE_MOTOR_OUTPUT) && \
     (TELEMETRY_SOURCE != TELEMETRY_SOURCE_FLIGHT_CONTROL))
#error "Invalid TELEMETRY_SOURCE"
#endif

#if ((TPF_FLOW_PIN_PAIR != TPF_FLOW_PIN_PAIR_P411_P412) && \
     (TPF_FLOW_PIN_PAIR != TPF_FLOW_PIN_PAIR_P413_P414) && \
     (TPF_FLOW_PIN_PAIR != TPF_FLOW_PIN_PAIR_P408_P409) && \
     (TPF_FLOW_PIN_PAIR != TPF_FLOW_PIN_PAIR_P400_P401) && \
     (TPF_FLOW_PIN_PAIR != TPF_FLOW_PIN_PAIR_P402_P403) && \
     (TPF_FLOW_PIN_PAIR != TPF_FLOW_PIN_PAIR_P404_P405) && \
     (TPF_FLOW_PIN_PAIR != TPF_FLOW_PIN_PAIR_P406_P407) && \
     (TPF_FLOW_PIN_PAIR != TPF_FLOW_PIN_PAIR_P406_P409))
#error "Invalid TPF_FLOW_PIN_PAIR"
#endif

#endif /* CODE_PROJECT_CONFIG_H_ */
